<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>

		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>

		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ApplicationIcon>assets\folderCustomizerIcon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="assets\folderCustomizerIcon.ico" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resource1.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resource1.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resource1.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resource1.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>